name = "tranquil"
description = "My fork of the Zola theme 'tranquil' by TeaDrinkingProgrammer"
license = "MIT"
homepage = "https://github.com/helibom/tranquil"
min_version = "0.1.0"

[author]
author = "helibom"
homepage = "https://github.com/helibom"
repo = "https://github.com/helibom/tranquil"

[original]
name = "TeaDrinkingProgrammer"
homepage = "https://github.com/TeaDrinkingProgrammer"
repo = "https://github.com/TeaDrinkingProgrammer/tranquil"
